export const NOTIFICATIONS_ACTION_TYPES = {
  ADD_NOTIFICATION_START: 'notifications/ADD_NOTIFICATION_START',
  ADD_NOTIFICATION_SUCCESS: 'notifications/ADD_NOTIFICATION_SUCCESS',
  ADD_NOTIFICATION_FAILED: 'notifications/ADD_NOTIFICATION_FAILED',
  CREATE_NOTIFICATION_DOC_START: 'notifications/CREATE_NOTIFICATION_DOC_START',
  CREATE_NOTIFICATION_DOC_SUCCESS: 'notifications/CREATE_NOTIFICATION_DOC_SUCCESS',
  CREATE_NOTIFICATION_DOC_FAILED: 'notifications/CREATE_NOTIFICATION_DOC_FAILED',
  GET_NOTIFICATIONS_START: 'notifications/GET_NOTIFICATIONS_START',
  GET_NOTIFICATIONS_SUCCESS: 'notifications/GET_NOTIFICATIONS_SUCCESS',
  GET_NOTIFICATIONS_FAILED: 'notifications/GET_NOTIFICATIONS_FAILED',
  REMOVE_NOTIFICATION_START: 'notifications/REMOVE_NOTIFICATION_START',
  REMOVE_NOTIFICATION_SUCCESS: 'notifications/REMOVE_NOTIFICATION_SUCCESS',
  REMOVE_NOTIFICATION_FAILED: 'notifications/REMOVE_NOTIFICATION_FAILED',
}