export const DISPLAY_ACTION_TYPES = {
  SET_SIGNIN_ERROR_OPEN: 'display/SET_SIGNIN_ERROR_OPEN',
  SET_SIGNUP_ERROR_OPEN: 'display/SET_SIGNUP_ERROR_OPEN',
  SET_ROOM_AVATAR_MODAL_OPEN: 'display/SET_ROOM_AVATAR_MODAL_OPEN',
  SET_LEFT_NAV_OPEN: 'display/SET_LEFT_NAV_OPEN',
  SET_MENU_OPEN: 'display/SET_MENU_OPEN',
  SET_ADD_ROOM_OPEN: 'display/SET_ADD_ROOM_OPEN',
  SET_SEARCH_OPEN: 'display/SET_SEARCH_OPEN',
  SET_STYLES_OPEN: 'display/SET_STYLES_OPEN',
  SET_LEFT_USER_ACTION_OPEN: 'display/SET_LEFT_USER_ACTION_OPEN',
  SET_NOTIFICATION_OPEN: 'display/SET_NOTIFICATION_OPEN',
  SET_CONTACT_MESSAGE: 'display/SET_CONTACT_MESSAGE'
}