export const CONTACTS_ACTION_TYPES = {
  GET_CONTACTS_START: 'contacts/GET_CONTACTS_START',
  GET_CONTACTS_SUCCESS: 'contacts/GET_CONTACTS_SUCCESS',
  GET_CONTACTS_FAILED: 'contacts/GET_CONTACTS_FAILED',
  GET_USER_MESSAGES_START: 'contacts/GET_USER_MESSAGES_START',
  GET_USER_MESSAGES_SUCCESS: 'contacts/GET_USER_MESSAGES_SUCCESS',
  GET_USER_MESSAGES_FAILED: 'contacts/GET_USER_MESSAGES_FAILED',
  ADD_CONTACTS_START: 'contacts/ADD_CONTACTS_START',
  ADD_CONTACTS_SUCCESS: 'contacts/ADD_CONTACTS_SUCCESS',
  ADD_CONTACTS_FAILED: 'contacts/ADD_CONTACTS_FAILED',
  CREATE_CONTACTS_DOC_START: 'contacts/CREATE_CONTACTS_DOC_START',
  CREATE_CONTACTS_DOC_SUCCESS: 'contacts/CREATE_CONTACTS_DOC_SUCCESS',
  CREATE_CONTACTS_DOC_FAILED: 'contacts/CREATE_CONTACTS_DOC_FAILED',
}