export const PENDING_CONTACTS_ACTION_TYPES = {
  GET_PENDING_CONTACTS: 'pendingContacts/GET_PENDING_CONTACTS',
  UPDATE_PENDING_CONTACTS_START: 'pendingContacts/UPDATE_PENDING_CONTACTS_START',
  UPDATE_PENDING_CONTACTS_SUCCESS: 'pendingContacts/UPDATE_PENDING_CONTACTS_SUCCESS',
  UPDATE_PENDING_CONTACTS_FAILED: 'pendingContacts/UPDATE_PENDING_CONTACTS_FAILED',
  REMOVE_PENDING_CONTACTS_START: 'pendingContacts/REMOVE_PENDING_CONTACTS_START',
  REMOVE_PENDING_CONTACTS_SUCCESS: 'pendingContacts/REMOVE_PENDING_CONTACTS_SUCCESS',
  REMOVE_PENDING_CONTACTS_FAILED: 'pendingContacts/REMOVE_PENDING_CONTACTS_FAILED'
}